trigger: none

#resources:
 # pipelines:
  #  - pipeline: trigger_pipeline
   #   source: 'thattonBL.GatewayRequestApi'
    #  project: 'Gateway'
     # trigger: true  # Enable trigger from GitHub Actions pipeline

pool:
  vmImage: 'ubuntu-latest'

variables:
  AZURE_CONTAINER_APP_NAME: 'gateway-request-api-iac'
  RESOURCE_GROUP: 'Gateway-Resources-IAC'
  DOCKER_IMAGE: 'attonbomb/gateway-request-api:latest'  # Replace with your Docker Hub image path

steps:
  - task: Docker@2
    inputs:
      command: 'login'
      containerRegistry: 'attonbomb-DockerHub-SC'

  - task: AzureCLI@2
    inputs:
      azureSubscription: 'Gateway-Resources-IAC-MI-Connection'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        echo "Updating Azure Container App with the latest image"

        # Update the Azure Container App to pull the latest image
        az containerapp update \
          --name gateway-request-api-iac
          --resource-group Gateway-IAC-Resources
          --image attonbomb/gateway-request-api:latest

        echo "Container App updated successfully"

