version: '3.4'

networks:
  gatewaynetwork:
    driver: bridge

volumes:
    gatewaydb_data:
      driver: local

services:
  gatewaydb:
    container_name: gateway-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    stdin_open: true
    ports:
        - "1433:1433"
    environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=password@12345#
    restart: always
    networks:
        - gatewaynetwork
    healthcheck:
      test: [ "CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P password@12345# -Q 'SELECT 1' || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    volumes:
         - ./gatewaydb_data:/docker-entrypoint-initdb.d
  gatewaydb.configurator:
      image: mcr.microsoft.com/mssql-tools:latest
      container_name: gateway-db-configurator
      user: root
      volumes:
         - ./gatewaydb_data:/docker-entrypoint-initdb.d
      depends_on:
         gatewaydb:
           condition: service_healthy
      command: bash -c '/opt/mssql-tools/bin/sqlcmd -S gateway-db -U sa -P password@12345# -i /docker-entrypoint-initdb.d/init.sql; echo "------------------------------ALLLL DONNNNNNEEEEEE!!!!---------------------------------";'
      networks:
         - gatewaynetwork
  gatewayrabbitmq:
    image: rabbitmq:3.13.1-management
    container_name: gateway-rabbitmq
    ports:
        - "15672:15672"
        - "5672:5672"
    networks:
        - gatewaynetwork
  gatewayrequestapi:
        container_name: gateway-req-api
        image: ${DOCKER_REGISTRY-}gatewayrequestapi
        build:
            context: .
            dockerfile: GatewayRequestApi/Dockerfile
        depends_on:
          - gatewaydb
          - gatewayrabbitmq
        environment:
          # - SQL_DB_CONNECTION_STRING=Data Source=gateway-db;Database=Gateway;Integrated Security=False;User ID=---user---;Password=----hidden-Vale----password@12345#;MultipleActiveResultSets=false;TrustServerCertificate=True;
          # - APPLICATIONINSIGHTS_CONNECTION_STRING=--------------------InstrumentationKey------------------;
          # - AZURE_SERVICE_BUS_CONNECTION_STRING=Endpoint=sb://gateway-messaging.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=-----hidden----Value------;
          - MSG_HOST=gateway-rabbitmq
        networks:
          - gatewaynetwork
