name: Build and Publish Docker Image to Docker Hub and Trigger Azure Release

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up .NET environment
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

      # Step 3: Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # Step 4: Run Unit Tests
      - name: Run Unit Tests
        run: dotnet test GatewayRequestApi.UnitTests/GatewayRequestApi.UnitTests.csproj --no-build --verbosity normal

      # Step 5: Run Functional Tests
      - name: Run Functional Tests
        run: dotnet test GatewayRequestApi.FunctionalTests/GatewayRequestApi.FunctionalTests.csproj --no-build --verbosity normal

      # Step 6: Login to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      # Step 7: Build the Docker image
      - name: Build Docker image
        run: |
          docker build --build-arg AZURE_DEVOPS_PAT=${{ secrets.AZURE_DEVOPS_PAT }} -t ${{ secrets.DOCKER_HUB_USERNAME }}/gateway-request-api:dev -f GatewayRequestApi/Dockerfile .

      # Step 8: Push Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/gateway-request-api:dev

      # Step 9: Trigger Azure Release Pipeline
      - name: Trigger Azure DevOps Pipeline
        uses: Azure/pipelines@v1.2
        with:
          azure-devops-project-url: ${{ secrets.AZURE_DEVOPS_PROJECT_URL }}
          azure-pipeline-name: 'thattonBL.GatewayRequestApi'
          azure-devops-token: ${{ secrets.AZURE_DEVOPS_PAT }}
      
      - uses: actions/checkout@v2
